## $\color{red}{\text{Python Packages and Data Structures}}$
### $\color{BLUE}{\text{Introduction to Packages}}$

1. Python packages or libraries are a collection of **functions** designed for speicific tasks
2. Python has **base** packages, while others need to be manually installed
3. Packages need to be imported before it can be used

### $\color{BLUE}{\text{Introduction to Data Structures}}$

1. What are data structures?
    - A way to store and organize data for the purpose of effective management
    - Data structures are different from data types

## $\color{red}{\text{Common Python Data Structures}}$
### $\color{blue}{\text{Lists}}$

1. Lists are a way to store information in the same variable
2. Lists are created in two ways:
    1. Using the brackets - []
    2. Using the list() function

#### $\color{green}{\text{Example 1}}$
1. Create a variable that stores the age of five (5) people
2. Create a variable that stores that stores three (3) fruit names
3. Create a variable that stores three (3) eye colors

In [1]:
ages = [10, 20, 30, 40, 50]
fruits = ["apple", "pear", "banana"]
eye_colors = ["hazel", "green", "brown"]

### $\color{blue}{\text{Operations on Lists: Indexing and Slicing}}$
1. Identify and select various elements in a list
2. Python is zero-based index
    - Meaning: the first element in a list has position 0

### $\color{blue}{\text{Operations on Lists: Inserting and Deletion}}$

1. Insertion provides a way to insert new elements into a list
2. Deletion provides a way to delete elements from a list

#### $\color{green}{\text{Example 2}}$
1. Select the first element of the list in the example above
2. Delete elements from a list
    - **list.remove()** - Removes the first instance of an element
3. Insert elements into a list
    - **list.insert(position, element)** - Inserts an element in a desired position

In [19]:
x = [0,1,2,3,4,5,6,7,8,9,10,11,12,1,2,3,4,5,6,7,8,9,10]
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [21]:
# REMOVING ITEMS FROM ARRS

x = [0,1,2,3,4,5,6,7,8,9,10,11,12,1,2,3,4,5,6,7,8,9,10]
x.pop() # removes the element at the last index of the array
x.remove(1) # removes the first instance of the number "1"
x

[0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
# ADDING ITEMS TO ARRS

x = ['a','b','c','d']
x.append('e')
x.insert(0,'z')
x

['z', 'a', 'b', 'c', 'd', 'e']

In [35]:
age = [1,2,3]
age2 = [1,2,3]
age3 = age+age2
age3

[1, 2, 3, 1, 2, 3]

## $\color{red}{\text{Common Python Data Structures}}$
### $\color{blue}{\text{Arrays: Numpy}}$

1. Numpy is a package that needs to be imported
2. Useful for computations - better than lists
3. Faster computation
4. It's a data type on its own - ndarray

#### $\color{green}{\text{Example 3}}$
1. Create three (3) numpy arrays
2. Use a function to create an array

In [37]:
import numpy as np

x1 = np.zeros(6, np.int64)
print(x1)

x2 = np.ones(7, np.int64)
print(x2)

x3 = np.array([0,1,2,3,4,5,6,7,8,9])
print(x3)

[0 0 0 0 0 0]
[1 1 1 1 1 1 1]
[0 1 2 3 4 5 6 7 8 9]


### $\color{blue}{\text{Operations on Numpy Arrays: Arithmetic}}$

1. Addition, Subtraction, Exponent
2. Multiplication and Division are different

#### $\color{green}{\text{Example 4}}$
1. Perform arithmetic operations on the arrays created in Example 3

In [39]:
x3 = x3 * 2
x3

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

## $\color{red}{\text{Common Python Data Structures}}$
### $\color{blue}{\text{Pandas DataFrame and Series}}$

1. Pandas is used for manipulating tabular data
2. Along with Numpy, it can provide statistical capabilities
2. They provide an "excel-like" feeling to analysis

In [41]:
import pandas as pd

df = pd.read_excel("/Users/dB/Desktop/spring_25/ds4510/notebooks/NBA.xlsx")
df

Player               Name Position  Age  Height  Weight     Salary  \
0          25  Metta World Peace       SF   36      79     260   947276.0   
1          25  Metta World Peace       SF   36      79     260   947276.0   
2          25  Metta World Peace       SF   36      79     260   947276.0   
3          25  Metta World Peace       SF   36      79     260   947276.0   
4          25  Metta World Peace       SF   36      79     260   947276.0   
...       ...                ...      ...  ...     ...     ...        ...   
5185  3892818    Emmanuel Mudiay       PG   20      77     200  3102240.0   
5186  3911666       Luis Montero       SG   23      79     185   525093.0   
5187  3911666       Luis Montero       SG   23      79     185   525093.0   
5188  3911666       Luis Montero       SG   23      79     185   525093.0   
5189  3911666       Luis Montero       SG   23      79     185   525093.0   

                   Season  Postseason Team  ...  FT_attempted  FT_percent  \
0                 '99-'00       False  CHI  ...           3.9       0.674   
1                 '00-'01       False  CHI  ...           3.7       0.750   
2                 '01-'02       False  CHI  ...           4.8       0.628   
3                 '01-'02       False  IND  ...           2.7       0.733   
4                 '02-'03       False  IND  ...           5.4       0.736   
...                   ...         ...  ...  ...           ...         ...   
5185  No stats available.        True  NaN  ...           NaN         NaN   
5186              '15-'16       False  POR  ...           0.3       0.750   
5187               Career       False  NaN  ...           0.3       0.750   
5188              '15-'16        True  POR  ...           0.0       0.000   
5189               Career        True  NaN  ...           0.0       0.000   

      Rebound_off  Rebound_def  Assists  Blocks  Steals  Fouls  Turnovers  \
0             0.9          3.4      2.8     0.5     1.7    2.2        2.3   
1             0.8          3.1      3.0     0.6     2.0    3.3        2.1   
2             1.5          3.4      2.9     0.9     2.8    4.0        2.6   
3             1.2          3.8      1.8     0.6     2.4    3.9        1.8   
4             1.5          3.8      2.9     0.7     2.3    3.5        2.1   
...           ...          ...      ...     ...     ...    ...        ...   
5185          NaN          NaN      NaN     NaN     NaN    NaN        NaN   
5186          0.0          0.3      0.1     0.0     0.0    0.1        0.3   
5187          0.0          0.3      0.1     0.0     0.0    0.1        0.3   
5188          0.0          0.0      0.0     0.0     0.0    0.2        0.0   
5189          0.0          0.0      0.0     0.0     0.0    0.2        0.0   

      Points  
0       12.0  
1       11.9  
2       15.6  
3       10.9  
4       15.5  
...      ...  
5185     NaN  
5186     1.2  
5187     1.2  
5188     1.3  
5189     1.3  

[5190 rows x 30 columns]

### $\color{blue}{\text{Operations on a DataFrame: Data Analysis and Statistics}}$

1. How many rows and columns does the data have?
2. View the first and last set of rows
3. Provide statistical summary of data

### $\color{green}{\text{Example 5}}$

1. Print the first five (5) rows of the data
2. How many rows and columns are in the data?
3. Provide a statistical summary of the data

In [42]:
df.head()

Player               Name Position  Age  Height  Weight    Salary   Season  \
0      25  Metta World Peace       SF   36      79     260  947276.0  '99-'00   
1      25  Metta World Peace       SF   36      79     260  947276.0  '00-'01   
2      25  Metta World Peace       SF   36      79     260  947276.0  '01-'02   
3      25  Metta World Peace       SF   36      79     260  947276.0  '01-'02   
4      25  Metta World Peace       SF   36      79     260  947276.0  '02-'03   

   Postseason Team  ...  FT_attempted  FT_percent  Rebound_off  Rebound_def  \
0       False  CHI  ...           3.9       0.674          0.9          3.4   
1       False  CHI  ...           3.7       0.750          0.8          3.1   
2       False  CHI  ...           4.8       0.628          1.5          3.4   
3       False  IND  ...           2.7       0.733          1.2          3.8   
4       False  IND  ...           5.4       0.736          1.5          3.8   

   Assists  Blocks  Steals  Fouls  Turnovers  Points  
0      2.8     0.5     1.7    2.2        2.3    12.0  
1      3.0     0.6     2.0    3.3        2.1    11.9  
2      2.9     0.9     2.8    4.0        2.6    15.6  
3      1.8     0.6     2.4    3.9        1.8    10.9  
4      2.9     0.7     2.3    3.5        2.1    15.5  

[5 rows x 30 columns]

In [46]:
rownums, colnums = df.shape
print(f'there are {colnums} columns and {rownums} rows in the dataframe')

there are 30 columns and 5190 rows in the dataframe


In [48]:
df.describe()

Player          Age       Height       Weight        Salary  \
count  5.190000e+03  5190.000000  5190.000000  5190.000000  5.075000e+03   
mean   4.078431e+05    29.458574    79.113102   222.640848  6.018327e+06   
std    9.775887e+05     4.639034     3.441178    26.408908  5.837336e+06   
min    2.500000e+01    19.000000    69.000000   161.000000  3.088800e+04   
25%    2.229750e+03    26.000000    76.000000   200.000000  1.270964e+06   
50%    3.276000e+03    29.000000    80.000000   225.000000  4.000000e+06   
75%    6.443000e+03    33.000000    82.000000   245.000000  8.500000e+06   
max    3.911666e+06    40.000000    87.000000   307.000000  2.500000e+07   

       Games_played  Games_started      Minutes      FG_made  FG_attempted  \
count   5073.000000    5073.000000  5073.000000  5073.000000   5073.000000   
mean      70.828701      40.481372    23.698048     3.759373      8.328760   
std      133.704988      98.624787    10.532366     2.364962      5.075063   
min        1.000000       0.000000     0.700000     0.000000      0.000000   
25%       12.000000       1.000000    15.800000     1.900000      4.300000   
50%       48.000000      11.000000    24.500000     3.400000      7.500000   
75%       76.000000      54.000000    32.500000     5.300000     11.700000   
max     1462.000000    1425.000000    46.500000    12.400000     27.200000   

       ...  FT_attempted  FT_percent  Rebound_off  Rebound_def      Assists  \
count  ...   5073.000000  5073.00000  5073.000000  5073.000000  5073.000000   
mean   ...      2.573625     0.70889     1.111394     3.113365     2.130298   
std    ...      2.166688     0.20662     0.946772     2.004178     1.991154   
min    ...      0.000000     0.00000     0.000000     0.000000     0.000000   
25%    ...      1.000000     0.66700     0.400000     1.700000     0.700000   
50%    ...      2.000000     0.75900     0.800000     2.700000     1.500000   
75%    ...      3.500000     0.82400     1.600000     4.100000     3.000000   
max    ...     14.700000     1.00000     6.000000    13.800000    12.800000   

            Blocks       Steals        Fouls   Turnovers       Points  
count  5073.000000  5073.000000  5073.000000  5073.00000  5073.000000  
mean      0.494520     0.734161     2.029194     1.38082    10.127853  
std       0.540597     0.491864     0.863381     0.91738     6.534283  
min       0.000000     0.000000     0.000000     0.00000     0.000000  
25%       0.100000     0.400000     1.500000     0.70000     5.000000  
50%       0.300000     0.700000     2.100000     1.20000     9.000000  
75%       0.700000     1.000000     2.600000     1.90000    14.100000  
max       4.300000     3.000000     6.000000     6.30000    35.400000  

[8 rows x 25 columns]